### PR TITLE
Update to Openwrt/LEDE 17.01 and get netifd setting IP 'out-of-the-box'

### PR DESCRIPTION
**Pull request by cshoredaniel**
The following patch series updates the Openwrt pulls to be from latest upstream stable which is lede-17.01 branch since the recently announced remerge of LEDE with Openwrt.

It takes care of a number of issue related to the upgrade.

It also configures /etc/config/network so that the image has a working IP 'out-of-the-box' even if (as is the default with OE) the kernel network bridge model is not enabled.

It has been 'lightly' tested with musl and glibc in both cases basic luci works, but there are a number of details to be worked on throughout the stack.

### CODE REVIEW

**Comment by kraj** [comment]
is this superceded by #29 ?

**Comment by cshoredaniel** [comment]
It can be...#29 was meant to be split out if discussion was needed, but I'm actually pretty happy with were it gets things (esp. once I fix the noted issues, and it seems to be mostly ok with you for the full set).

**Comment by kraj** [comment]
can this be closed ?

**Comment by cshoredaniel** [comment]
Superseded by accepted merge

**Pull request closed without merging**
