### PR TITLE
Added mainline linux support

### PR DESCRIPTION
**Pull request by katyo**

### CODE REVIEW

**Review by kraj — APPROVED** [review]

**Comment by katyo** [comment]
I have the following error with this fix when no any layers with mainline linux kernel in tree:

```
ERROR: No recipes in default available for:
  /home/builder/workspace/yocto/build-raspberrypi1/../meta-openwrt/recipes-kernel/linux/linux-mainline%.bbappend
```

I'm not so familiar with bitbake and oe but I would like to avoid similar issues in the future.
Is where any way to fix config for any linux kernel variant?

**Comment by kraj** [comment]
Ideallly these bbappends should be perhaps applied in BSP layers itself, and we should perhaps add an override to identify `openwrt` here. I think we should revert this particularfix here. 

You can use `BB_DANGLINGAPPENDS_WARNONLY ="1"`
which turns this error into warning but it still it ugly.

**Comment by katyo** [comment]
Seems simple renaming `linux-yocto%.bbappend` to `linux-%.bbappend` should works. (No any other linux-<name>%.bbappend required).

**Comment by kraj** [comment]
linux-% is too loose to match, there are non kernel recipes which start with `linux-`  e.g. `./meta-openembedded/meta-networking/recipes-support/linux-atm/linux-atm_2.5.2.bb` `./openembedded-core/meta/recipes-kernel/linux-firmware/linux-firmware_20210208.bb` etc.

**Comment by katyo** [comment]
Hmm, really.
But I wouldn't like to apply such fixes via configuration.

**Pull request merged**
